test for rsync

diff --git a/bin/eza-send b/bin/eza-send
--- a/bin/eza-send
+++ b/bin/eza-send
@@ -8,6 +8,10 @@ if [ "x" == "x${3}" ]; then
     echo "Usage: `basename -- $0` [-i] jailname user@remotehost:port remote_zfs_dataset"
     exit 1
 fi
+if ! which rsync >/dev/null ; then
+    echo "Can't find rsync."
+    exit 1
+fi
 if [ "x-i" == "x${1}" ]; then
     INCREMENTAL=1
     shift
